platform :ios do

  desc("Run SwiftLint")
  lane :swiftlint_run do |options|
    swiftlint(
    ignore_exit_status: true
    )
  end
 
  desc "Build project to folder"
  lane :build_for_testing do
    swiftlint_run
    cocoapods(
        try_repo_update_on_error: true
	)
	scan(
	   derived_data_path: "my_folder",
	   build_for_testing: true,
	   clean: true,
       xcargs: "CI=true"
	)
  end

  desc "Testing folder from folder"
  lane :test_run do
	scan(
  	   derived_data_path: "my_folder",
           test_without_building: true
	)
  end

  desc "Build and test"
  lane :build_and_test do |options|
	build_for_testing
	test_run
  end

end
