# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do

 desc "Build project to folder"
  lane :build_for_testing do
	cocoapods(
	try_repo_update_on_error: true
	)
	scan(
	   derived_data_path: "my_folder",
	   build_for_testing: true,
	   clean: true
	)
  end

  desc "Testing folder from folder"
  lane :test_run do
	scan(
  	   derived_data_path: "my_folder",
           test_without_building: true
	)
  end

  desc "Build and test"
  lane :build_and_test do |options|
	build_for_testing
	test_run
  end

end
