name: CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
  
    
    - name: Build and Run
      run: |
        bundle exec fastlane build_for_testing
        bundle exec fastlane tests_run
    - name: Show succes notify 
      uses: sarisia/actions-status-discord@v1
      if: success()
      with:
          webhook: ${{ secrets.WEBHOOK_URL }} 
          title: "test are good"
          description: "Build and deploy to GitHub Pages"
          color: 0x00ff00
          username: GitHub Notification
          avatar_url: ${{ secrets.AVATAR_URL }}
    - name: Show failed notify 
      uses: sarisia/actions-status-discord@v1      
      if: failure()
      with:
          webhook: ${{ secrets.WEBHOOK_URL }} 
          title: "test lost"
          description: "Build and deploy to GitHub Pages"
          color: 0xff0000
          username: GitHub Notification Failed
          avatar_url: ${{ secrets.AVATAR_URL }}
          image: ${{ secrets.AVATAR_URL }}

